### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by mcandre** [alexkohler/nakedret#36]
I'm trying to acquire nakedret v2.0.3, but the Go package structure doesn't appear to be setup correctly.

The latest git tag is v2.0.3. But the `latest` Go version points to v1.0.2. And attempts to pin the installation to v2.0.3 fail.

```console
$ go install github.com/alexkohler/nakedret/cmd/nakedret@latest
go: downloading github.com/alexkohler/nakedret v1.0.2

$ go install github.com/alexkohler/nakedret/cmd/nakedret@v2.0.3
go: github.com/alexkohler/nakedret/cmd/nakedret@v2.0.3: github.com/alexkohler/nakedret/cmd/nakedret@v2.0.3: invalid version: unknown revision cmd/nakedret/v2.0.3
```

**Comment by triarius** [comment]
@mcandre You need to add a `/v2` to the module path for the tags v2 and above. On my system:
```
❯ go install github.com/alexkohler/nakedret/v2/cmd/nakedret@v2.0.3
go: downloading github.com/alexkohler/nakedret/v2 v2.0.3
```
If you specify `@latest` you can get the latest v2 tag if you have v2 in the module path.

There's some more info in https://github.com/alexkohler/nakedret/pull/27#issue-1663284446

But IMO the README should be updated too, which is why I've raised a PR.
